### ISSUE TITLE
Github settings 

### ISSUE THREAD

**Issue by romanrostislavovich** [linterhub/registry#1]
Please, add github settings.

Settings must be include: 
- `labels` and repo settings
- PR template
- Issue template

**Comment by xferra** [comment]
Is it a good time to finish template repo or introduce some generators? (readme, gitignore, labels, .github folder, etc.)?

**Comment by romanrostislavovich** [comment]
Sounds good. Maybe you have some URLs on some generators or where I can find it?

**Comment by romanrostislavovich** [comment]
@xferra and this?)
