### ISSUE TITLE
Search the some package in npm 

### ISSUE THREAD

**Issue by romanrostislavovich** [linterhub/registry#2]
Need to find meta-information about some package in `npm` and return it in JSON Object format. 

Return object must be correspond to [package.json](schema.linterhub.com/package.json) schema

The implementation should take into account: 
- search meta-information on another package managers (new package manager will be added later)

For input methods can get: 
- origin name of package
- manager name 
- version (optional): `all` by default

**Comment by xferra** [comment]
I will say you need a function: 
```
search(name: string, version: string[] = null): [{package, deps}]
```
That will return an array of objects and each of them will contain package and dependency definitions for specific package version. If concrete version was not provided, then all versions should be returned. This function should be implemented for several package managers (TBD: npm, nuget, etc.)

**Comment by xferra** [comment]
Anyway I suggest to split this task, for example perform search request and mapping to `schemas` could be implemented in separate PRs.

**Comment by romanrostislavovich** [comment]
Schemas for outputs: 
- [`package.json`][schema-package]
- [`deps.json`][schema-deps]

In feature we support following package managers: 
- [`npm`][manager-npm]
- [`chocolatey`][manager-chocolatey]
- [`composer`][manager-composer]
- [`nuget`][manager-nuget]
- [`gem`][manager-gem]
- [`pip`][manager-pip]

[schema-package]: https://schema.linterhub.com/package.json
[schema-deps]: https://schema.linterhub.com/deps.json
[manager-chocolatey]: https://chocolatey.org
[manager-composer]: https://getcomposer.org
[manager-pip]: https://pypi.org/project/pip/
[manager-npm]: https://www.npmjs.com
[manager-nuget]:https://www.nuget.org
[manager-gem]: https://rubygems.org

e.t.c.

If have any idea about new methods, please describe it :)

**Comment by xferra** [comment]
@svoboda-rabstvo Please use a separate issue for proposals.

**Comment by romanrostislavovich** [comment]
@xferra I think we can close this issue?

**Comment by xferra** [comment]
As soon as issues for package managers listed above are created.

**Comment by romanrostislavovich** [comment]
@xferra Now we supported: `gem`, `composer`, `pip` and `npm`, and we have issue for [`chocolatey`](#7) and [`nuget`](#20)

**Comment by xferra** [comment]
Then just link corresponding issues to this one, please :)
