### ISSUE TITLE
Improve npm dependencies parsing

### ISSUE THREAD

**Issue by romanrostislavovich** [linterhub/registry#26]
NPM Package dependencies have `devDependencies` and `dependencies`, e.g.:

```
 "dependencies": {
    "optimist": "*",
    "astw": "*",
    "esprima": "*",
    "jshint": "*"
},
"devDependencies": {
    "vows": "~0.7.0",
    "istanbul": "~0.1.10",
    "sinon": "*",
},
```

This is all dependencies for `eslint` v0.0.4. I suggest creating separate property `dev` for dependency package. 

New property `dev` is `false` by default, but if package use only for development we set `true`.

Result by parsing for `eslint 0.0.4` look like:
```
[
    { manager: 'npm', package: 'optimist', version: '*' },
    { manager: 'npm', package: 'astw', version: '*' },
    { manager: 'npm', package: 'esprima', version: '*' },
    { manager: 'npm', package: 'jshint', version: '*' },
    { manager: 'npm', package: 'vows', version: '~0.7.0', dev: true },
    { manager: 'npm', package: 'istanbul', version: '~0.1.10', dev: true },
    { manager: 'npm', package: 'sinon', version: '*', dev: true },
]
```

**Comment by romanrostislavovich** [comment]
This purpose with new property actual for `gem` and `composer` package managers too

**Comment by romanrostislavovich** [comment]
So, we need to return only `dependencies`, which needs for correct works of the app. Please,  check the `getDeps` method for all managers

**Comment by doroxz-zz** [comment]
We don't need devDependencies. They are used for listing, building and testing. So, published npm package can be executed without them.
